from fpdf import FPDF
import datetime

class PDF(FPDF):
    def header(self):
        self.set_font('helvetica', 'B', 16)
        self.set_text_color(5, 150, 105) # Syngenta Green
        self.cell(0, 10, 'AgriAttribute AI - Syngenta ROI Report', border=False, align='C')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Generated by HACK CORE 2026 (Team 15) - Page {self.page_no()}', 0, 0, 'C')

def generate_roi_pdf(farm_info, roi_data, forecast_data):
    """
    Generates a PDF byte string containing the Farm info, ROI metrics, and 10-day forecast table.
    """
    pdf = PDF()
    pdf.add_page()
    
    # Section 1: Farm Details
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, 'Farm Profile & Biological Input', ln=True)
    
    pdf.set_font('helvetica', '', 11)
    for key, val in farm_info.items():
        pdf.cell(60, 8, f"{key}:", border=0)
        pdf.cell(0, 8, str(val), border=0, ln=True)
    pdf.ln(5)
    
    # Section 2: ROI Analysis
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Yield Attribution & Financial Impact (Per Acre)', ln=True)
    
    pdf.set_font('helvetica', '', 11)
    for key, val in roi_data.items():
        if "Boost" in key or "Profit" in key or "ROI" in key or "+" in str(val):
            pdf.set_text_color(5, 150, 105) # Green highlight
            pdf.set_font('helvetica', 'B', 11)
        else:
            pdf.set_text_color(15, 23, 42)
            pdf.set_font('helvetica', '', 11)
            
        pdf.cell(60, 8, f"{key}:", border=0)
        pdf.cell(0, 8, str(val), border=0, ln=True)
    
    pdf.ln(10)
    pdf.set_text_color(15, 23, 42)
    
    # Section 3: Weather Forecast
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, '10-Day Agronomic Weather Forecast (Meteoblue API)', ln=True)
    
    # Table Header
    pdf.set_font('helvetica', 'B', 10)
    pdf.set_fill_color(241, 245, 249)
    col_widths = [30, 45, 40, 35, 35]
    headers = ["Date", "Condition", "Temp (Max/Min)", "Humidity", "Wind"]
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 10, h, border=1, align='C', fill=True)
    pdf.ln()
    
    # Table Rows
    pdf.set_font('helvetica', '', 10)
    for day in forecast_data:
        pdf.cell(col_widths[0], 10, str(day['date']), border=1, align='C')
        pdf.cell(col_widths[1], 10, str(day['condition']), border=1, align='C')
        pdf.cell(col_widths[2], 10, f"{day['temp_max']}/{day['temp_min']} C", border=1, align='C')
        pdf.cell(col_widths[3], 10, f"{day['humidity_pct']}%", border=1, align='C')
        pdf.cell(col_widths[4], 10, f"{day['wind_kmh']} km/h", border=1, align='C')
        pdf.ln()
        
    return pdf.output(dest='S')
